FROM debian:wheezy

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=trigger/trigger
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY trigger.tar.gz /trigger.tar.gz
RUN tar -xvf /trigger.tar.gz

#ADD . /trigger
RUN cd /trigger/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /trigger && scripts/windows-crosscompile/compile-trigger.sh
